// ─── Shops matching the reference site exactly ───────────────────────────────
export const MOCK_SHOPS = [
    {
        id: "shop-heritage-couture",
        name: "Heritage Couture",
        slug: "heritage-couture",
        owner_name: "Ananya Sharma",
        owner_email: "ananya@heritagecouture.in",
        city: "Jaipur",
        country: "India",
        specialty: "Bridal lehengas and couture sets",
        description: "Jaipur's finest bridal and festive couture house. Handcrafted pieces for life's most special moments.",
        image_url: "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?w=800&q=80",
        instagram_url: "https://instagram.com/heritagecouture",
        is_active: true,
        rating: 4.9,
        followers: 12400,
        productCount: 87,
        trending: false,
        featured: true,
        deliveryDays: 4,
        shippingEstimate: "4-7 days",
        verified: true,
    },
    {
        id: "shop-royal-threads-jaipur",
        name: "Royal Threads Jaipur",
        slug: "royal-threads-jaipur",
        owner_name: "Vikram Singh",
        owner_email: "vikram@royalthreads.in",
        city: "Jaipur",
        country: "India",
        specialty: "Sherwanis, kurtas and men's ethnic wear",
        description: "Jaipur's premier destination for men's traditional clothing — from royal sherwanis to everyday kurtas.",
        image_url: "https://images.unsplash.com/photo-1760080838961-4208536db385?w=800&q=80",
        instagram_url: "https://instagram.com/royalthreadsjaipur",
        is_active: true,
        rating: 4.7,
        followers: 8900,
        productCount: 64,
        trending: true,
        featured: true,
        deliveryDays: 3,
        shippingEstimate: "3-5 days",
        verified: true,
    },
    {
        id: "shop-banarasi-silks-co",
        name: "Banarasi Silks Co.",
        slug: "banarasi-silks-co",
        owner_name: "Meera Gupta",
        owner_email: "meera@banarasisilks.in",
        city: "Varanasi",
        country: "India",
        specialty: "Authentic Banarasi silk sarees and tissue sarees",
        description: "Third-generation weavers from the banks of the Ganga. Every saree is a masterpiece of Varanasi's ancient craft.",
        image_url: "https://images.unsplash.com/photo-1619516388835-2b60acc4049e?w=800&q=80",
        instagram_url: "https://instagram.com/banarasisilkco",
        is_active: true,
        rating: 4.9,
        followers: 21000,
        productCount: 143,
        trending: true,
        featured: true,
        deliveryDays: 3,
        shippingEstimate: "3-6 days",
        verified: true,
    },
    {
        id: "shop-garba-trends-surat",
        name: "Garba Trends Surat",
        slug: "garba-trends-surat",
        owner_name: "Pooja Patel",
        owner_email: "pooja@garbatrends.in",
        city: "Surat",
        country: "India",
        specialty: "Chaniya choli, navratri and festive wear",
        description: "Surat's most celebrated chaniya choli house. Navratri, festivals and weddings — we dress you for every celebration.",
        image_url: "https://images.unsplash.com/photo-1668371679302-a8ec781e876e?w=800&q=80",
        instagram_url: "https://instagram.com/garbatrends",
        is_active: true,
        rating: 4.8,
        followers: 15600,
        productCount: 112,
        trending: true,
        featured: false,
        deliveryDays: 2,
        shippingEstimate: "2-4 days",
        verified: true,
    },
    {
        id: "shop-mumbai-kids-studio",
        name: "Mumbai Kids Studio",
        slug: "mumbai-kids-studio",
        owner_name: "Sunita Rele",
        owner_email: "sunita@mumbaikids.in",
        city: "Mumbai",
        country: "India",
        specialty: "Kids traditional wear and festive outfits",
        description: "India's favourite destination for children's traditional clothing. Adorable, comfortable, and crafted to last.",
        image_url: "https://images.unsplash.com/photo-1605292356183-a77d0a9c9d1d?w=800&q=80",
        instagram_url: "https://instagram.com/mumbaikidsstudio",
        is_active: true,
        rating: 4.6,
        followers: 7200,
        productCount: 55,
        trending: false,
        featured: false,
        deliveryDays: 4,
        shippingEstimate: "4-6 days",
        verified: true,
    },
    {
        id: "shop-delhi-wedding-house",
        name: "Delhi Wedding House",
        slug: "delhi-wedding-house",
        owner_name: "Rahul Kapoor",
        owner_email: "rahul@delhiwedding.in",
        city: "Delhi",
        country: "India",
        specialty: "Bridal and wedding guest collections",
        description: "Delhi's most trusted wedding wear curator. Bridal, groom, and family ensembles for the perfect wedding day.",
        image_url: "https://images.unsplash.com/photo-1703045199207-5312874d9e54?w=800&q=80",
        instagram_url: "https://instagram.com/delhiweddinghouse",
        is_active: true,
        rating: 4.8,
        followers: 18300,
        productCount: 98,
        trending: false,
        featured: true,
        deliveryDays: 3,
        shippingEstimate: "3-5 days",
        verified: true,
    },
];

// ─── Products matching the reference site exactly ─────────────────────────────
export const MOCK_PRODUCTS = [
    // ── Featured products (reference site "Featured This Season") ──
    {
        id: "fp1",
        shop_id: "shop-heritage-couture",
        shop_name: "Heritage Couture",
        name: "Couple Matching Set — Ivory & Gold",
        slug: "couple-matching-set-ivory-gold",
        category: "Wedding Wear",
        description: "A stunning couple matching set in ivory and gold. Perfect for sangeet, mehendi or a wedding reception. Handcrafted with zardozi embroidery by Jaipur artisans.",
        price: 44999,
        compare_at_price: 64999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1656402356161-cf01c632c1bc?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1703045199207-5312874d9e54?w=900&q=85",
        stock: 3,
        badge: "HERITAGE COUTURE",
        is_featured: true,
        is_active: true,
        color: "Ivory",
        ready_to_ship: false,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp2",
        shop_id: "shop-royal-threads-jaipur",
        shop_name: "Royal Threads Jaipur",
        name: "Ivory Royal Sherwani with Gold Embroidery",
        slug: "ivory-royal-sherwani-gold-embroidery",
        category: "Sherwanis",
        description: "A majestic ivory sherwani with intricate gold embroidery. Tailored for the modern groom who wants to honour tradition with grace.",
        price: 27999,
        compare_at_price: 38999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1760080838961-4208536db385?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1681717055630-c62333c22fec?w=900&q=85",
        stock: 5,
        badge: "ROYAL THREADS JAIPUR",
        is_featured: true,
        is_active: true,
        color: "Ivory",
        ready_to_ship: false,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp3",
        shop_id: "shop-banarasi-silks-co",
        shop_name: "Banarasi Silks Co.",
        name: "Ivory Tissue Saree with Real Zari",
        slug: "ivory-tissue-saree-real-zari",
        category: "Sarees",
        description: "Woven by master craftsmen in Varanasi — this ivory tissue saree with real gold zari is an heirloom piece. Each saree takes 15 days to weave.",
        price: 24999,
        compare_at_price: 34999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1619516388835-2b60acc4049e?w=900&q=85",
        stock: 4,
        badge: "BANARASI SILKS CO.",
        is_featured: true,
        is_active: true,
        color: "Ivory",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp4",
        shop_id: "shop-heritage-couture",
        shop_name: "Heritage Couture",
        name: "Pastel Pink Embroidered Lehenga Set",
        slug: "pastel-pink-embroidered-lehenga-set",
        category: "Lehengas",
        description: "A dreamy pastel pink lehenga set with hand-embroidered floral motifs. The perfect bridal or sangeet outfit for the modern Indian woman.",
        price: 39999,
        compare_at_price: 56999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1668371459824-094a960a227d?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?w=900&q=85",
        stock: 2,
        badge: "HERITAGE COUTURE",
        is_featured: true,
        is_active: true,
        color: "Pastel Pink",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp5",
        shop_id: "shop-royal-threads-jaipur",
        shop_name: "Royal Threads Jaipur",
        name: "Navy Silk Kurta with Mirror Work",
        slug: "navy-silk-kurta-mirror-work",
        category: "Kurtas",
        description: "A rich navy silk kurta adorned with hand-stitched mirror work. Pair with white churidar for a timeless festive look.",
        price: 8999,
        compare_at_price: 12999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1727835523545-70ee992b5763?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1744551358303-46edae8b374b?w=900&q=85",
        stock: 8,
        badge: "ROYAL THREADS JAIPUR",
        is_featured: true,
        is_active: true,
        color: "Navy",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp6",
        shop_id: "shop-banarasi-silks-co",
        shop_name: "Banarasi Silks Co.",
        name: "Royal Banarasi Silk Saree — Maroon & Gold",
        slug: "royal-banarasi-silk-saree-maroon-gold",
        category: "Sarees",
        description: "The queen of all sarees — a pure Banarasi silk in royal maroon with gold brocade. A treasure passed down through generations.",
        price: 19999,
        compare_at_price: 28999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1619516388835-2b60acc4049e?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?w=900&q=85",
        stock: 6,
        badge: "BANARASI SILKS CO.",
        is_featured: true,
        is_active: true,
        color: "Maroon",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp7",
        shop_id: "shop-heritage-couture",
        shop_name: "Heritage Couture",
        name: "Maharani Bridal Lehenga — Crimson Velvet",
        slug: "maharani-bridal-lehenga-crimson-velvet",
        category: "Lehengas",
        description: "The Maharani — our most iconic bridal lehenga in deep crimson velvet with gold zardozi. Worn by brides across three continents.",
        price: 64999,
        compare_at_price: 89999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1668371459824-094a960a227d?w=900&q=85",
        stock: 1,
        badge: "HERITAGE COUTURE",
        is_featured: true,
        is_active: true,
        color: "Crimson",
        ready_to_ship: false,
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "fp8",
        shop_id: "shop-garba-trends-surat",
        shop_name: "Garba Trends Surat",
        name: "Navratri Rani Pink Chaniya Choli",
        slug: "navratri-rani-pink-chaniya-choli",
        category: "Chaniya Choli",
        description: "Dance the nights of Navratri in this vibrant rani pink chaniya choli. Full flare, comfortable fabric, and intricate mirror and thread work.",
        price: 9999,
        compare_at_price: 15999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1668371679302-a8ec781e876e?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1468234847176-28606331216a?w=900&q=85",
        stock: 12,
        badge: "GARBA TRENDS SURAT",
        is_featured: true,
        is_active: true,
        color: "Rani Pink",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    // ── New Arrivals ──
    {
        id: "na1",
        shop_id: "shop-royal-threads-jaipur",
        shop_name: "Royal Threads Jaipur",
        name: "Cream Linen Kurta Pyjama Set",
        slug: "cream-linen-kurta-pyjama-set",
        category: "Kurtas",
        description: "Relaxed yet refined — this cream linen kurta pyjama set is perfect for daytime celebrations or casual festive wear.",
        price: 5999,
        compare_at_price: 8999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1744551358303-46edae8b374b?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1727835523545-70ee992b5763?w=900&q=85",
        stock: 15,
        badge: "ROYAL THREADS JAIPUR",
        is_featured: false,
        is_active: true,
        color: "Cream",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na2",
        shop_id: "shop-garba-trends-surat",
        shop_name: "Garba Trends Surat",
        name: "Navratri Rani Pink Chaniya Choli",
        slug: "navratri-rani-pink-chaniya-choli-na",
        category: "Chaniya Choli",
        description: "Back by popular demand — our bestselling rani pink chaniya choli for Navratri. Limited stock available.",
        price: 9999,
        compare_at_price: 15999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1668371679302-a8ec781e876e?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1468234847176-28606331216a?w=900&q=85",
        stock: 9,
        badge: "GARBA TRENDS SURAT",
        is_featured: false,
        is_active: true,
        color: "Rani Pink",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na3",
        shop_id: "shop-heritage-couture",
        shop_name: "Heritage Couture",
        name: "Pastel Pink Embroidered Lehenga Set",
        slug: "pastel-pink-lehenga-new",
        category: "Lehengas",
        description: "New season restock of our most-loved pastel pink lehenga. Updated with fresh embroidery details.",
        price: 39999,
        compare_at_price: 56999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1668371459824-094a960a227d?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?w=900&q=85",
        stock: 3,
        badge: "HERITAGE COUTURE",
        is_featured: false,
        is_active: true,
        color: "Pastel Pink",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na4",
        shop_id: "shop-royal-threads-jaipur",
        shop_name: "Royal Threads Jaipur",
        name: "Maroon Velvet Bandhgala Sherwani",
        slug: "maroon-velvet-bandhgala-sherwani",
        category: "Sherwanis",
        description: "A bold maroon velvet bandhgala sherwani for grooms who command the room. Paired with ivory accessories for contrast.",
        price: 22999,
        compare_at_price: 32999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1681717055630-c62333c22fec?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1760080838961-4208536db385?w=900&q=85",
        stock: 4,
        badge: "ROYAL THREADS JAIPUR",
        is_featured: false,
        is_active: true,
        color: "Maroon",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na5",
        shop_id: "shop-garba-trends-surat",
        shop_name: "Garba Trends Surat",
        name: "Yellow Cotton Chaniya Choli — Garba Special",
        slug: "yellow-cotton-chaniya-choli-garba",
        category: "Chaniya Choli",
        description: "Sunshine yellow cotton chaniya choli designed for long Garba nights. Breathable, beautiful, and built to dance.",
        price: 5499,
        compare_at_price: 8999,
        currency: "INR",
        image_url: "https://images.pexels.com/photos/20158862/pexels-photo-20158862.jpeg?w=900",
        hover_image_url: "https://images.unsplash.com/photo-1668371679302-a8ec781e876e?w=900&q=85",
        stock: 18,
        badge: "GARBA TRENDS SURAT",
        is_featured: false,
        is_active: true,
        color: "Yellow",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na6",
        shop_id: "shop-heritage-couture",
        shop_name: "Heritage Couture",
        name: "Maharani Bridal Lehenga — Crimson Velvet",
        slug: "maharani-bridal-lehenga-new",
        category: "Lehengas",
        description: "New production run of the iconic Maharani. Reserve yours today — only 2 pieces available this season.",
        price: 64999,
        compare_at_price: 89999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1668371459824-094a960a227d?w=900&q=85",
        stock: 2,
        badge: "HERITAGE COUTURE",
        is_featured: false,
        is_active: true,
        color: "Crimson",
        ready_to_ship: false,
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na7",
        shop_id: "shop-royal-threads-jaipur",
        shop_name: "Royal Threads Jaipur",
        name: "Navy Silk Kurta with Mirror Work",
        slug: "navy-silk-kurta-new",
        category: "Kurtas",
        description: "Restocked. Our most loved kurta in deep navy silk with hand-stitched mirror work is back.",
        price: 8999,
        compare_at_price: 12999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1727835523545-70ee992b5763?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1744551358303-46edae8b374b?w=900&q=85",
        stock: 6,
        badge: "ROYAL THREADS JAIPUR",
        is_featured: false,
        is_active: true,
        color: "Navy",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "na8",
        shop_id: "shop-banarasi-silks-co",
        shop_name: "Banarasi Silks Co.",
        name: "Ivory Tissue Saree with Real Zari",
        slug: "ivory-tissue-saree-new",
        category: "Sarees",
        description: "New weave just arrived from the looms of Varanasi. Pure tissue with real gold zari — collector's piece.",
        price: 24999,
        compare_at_price: 34999,
        currency: "INR",
        image_url: "https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?w=900&q=85",
        hover_image_url: "https://images.unsplash.com/photo-1619516388835-2b60acc4049e?w=900&q=85",
        stock: 3,
        badge: "BANARASI SILKS CO.",
        is_featured: false,
        is_active: true,
        color: "Ivory",
        ready_to_ship: true,
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
];

export const MOCK_COLLECTIONS = [
    { id: "coll_1", name: "Bridal Collection", slug: "bridal", description: "Complete bridal sets for the modern Indian bride." },
    { id: "coll_2", name: "Festive Essentials", slug: "festive", description: "Diwali, Navratri, Eid — be ready for every celebration." },
    { id: "coll_3", name: "Wedding Guest", slug: "wedding-guest", description: "Look stunning at every wedding on your calendar." },
    { id: "coll_4", name: "Men's Ethnic", slug: "mens-ethnic", description: "Sherwanis, kurtas and bandhgalas for every occasion." },
    { id: "coll_5", name: "Kids Traditional", slug: "kids", description: "Adorable traditional wear for your little ones." },
    { id: "coll_6", name: "Ready to Ship", slug: "ready-to-ship", description: "Need it fast? These pieces ship within 24 hours." },
];
