// Test data for development and debugging
export const MOCK_SHOPS = [
    {
        id: "shop_1",
        name: "Jaipur Atelier House",
        slug: "jaipur-atelier-house",
        owner_name: "Aarav Mehta",
        owner_email: "aarav@shoplivebharat.com",
        city: "Ahmedabad",
        country: "India",
        specialty: "Festive lehengas and mirrorwork jackets",
        description: "A family-run atelier curating festive silhouettes, light occasion wear and handcrafted embellishment for live video discovery. Specializing in traditional Gujarati embroidery with modern fusion designs.",
        image_url: "/shop-assets/banner-1.jpg",
        instagram_url: "https://instagram.com/jaipur-atelier",
        is_active: true
    },
    {
        id: "shop_2",
        name: "The Banaras Edit",
        slug: "the-banaras-edit",
        owner_name: "Meera Shah",
        owner_email: "meera@shoplivebharat.com",
        city: "Ahmedabad",
        country: "India",
        specialty: "Silk drapes, jewellery and wedding guest edits",
        description: "A curated saree and accessory house focused on timeless wedding wardrobes for Indians shopping from abroad. Featuring authentic Banarasi silk with Ahmedabad's traditional craftsmanship.",
        image_url: "/shop-assets/womens-banner.jpg",
        instagram_url: "https://instagram.com/banaras-edit",
        is_active: true
    },
    {
        id: "shop_3",
        name: "Ahmedabad Heritage",
        slug: "ahmedabad-heritage",
        owner_name: "Rajesh Patel",
        owner_email: "rajesh@shoplivebharat.com",
        city: "Ahmedabad",
        country: "India",
        specialty: "Traditional Gujarati embroidery and bandhani",
        description: "Preserving Ahmedabad's rich textile heritage through traditional bandhani, tie-and-dye techniques, and intricate hand embroidery. Featuring authentic pieces made by local artisans.",
        image_url: "/shop-assets/banner-2.jpg",
        instagram_url: "https://instagram.com/ahmedabad-heritage",
        is_active: true
    },
    {
        id: "shop_4",
        name: "Modern Threads Ahmedabad",
        slug: "modern-threads-ahmedabad",
        owner_name: "Priya Desai",
        owner_email: "priya@shoplivebharat.com",
        city: "Ahmedabad",
        country: "India",
        specialty: "Contemporary fusion wear with traditional elements",
        description: "Blending modern fashion with traditional Ahmedabad crafts. Creating fusion pieces that appeal to contemporary Indian women while honoring local textile traditions.",
        image_url: "/shop-assets/womens-banner.jpg",
        instagram_url: "https://instagram.com/modern-threads",
        is_active: true
    },
    {
        id: "shop_5",
        name: "Crafted by Ahmedabad",
        slug: "crafted-by-ahmedabad",
        owner_name: "Vikram Singh",
        owner_email: "vikram@shoplivebharat.com",
        city: "Ahmedabad",
        country: "India",
        specialty: "Handwoven textiles and artisan collaborations",
        description: "Showcasing handwoven textiles and direct collaborations with Ahmedabad's artisan community. Each piece tells a story of traditional craftsmanship and sustainable practices.",
        image_url: "/shop-assets/banner-3.jpg",
        instagram_url: "https://instagram.com/crafted-ahmedabad",
        is_active: true
    }
];

export const MOCK_PRODUCTS = [
    // Jaipur Atelier House - Ahmedabad
    {
        id: "prod_1",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Kantha Wrap Jacket",
        slug: "kantha-wrap-jacket",
        category: "Outerwear",
        description: "A hand-finished wrap jacket for festive layering and destination wedding wardrobes. Features intricate kantha embroidery with traditional motifs.",
        price: 6490,
        compare_at_price: 8290,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 8,
        badge: "Live Pick",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_2",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Mirror Work Lehenga",
        slug: "mirror-work-lehenga",
        category: "Lehenga",
        description: "Stunning lehenga with mirror work embellishment. Perfect for festivals and celebrations.",
        price: 8990,
        compare_at_price: 11990,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 5,
        badge: "Premium",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_3",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Traditional Festive Dupatta",
        slug: "festive-dupatta",
        category: "Accessories",
        description: "Hand-embroidered festive dupatta with traditional patterns. Versatile accessory for any occasion.",
        price: 2490,
        compare_at_price: 3490,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 15,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
    },
    // The Banaras Edit - Ahmedabad
    {
        id: "prod_4",
        shop_id: "shop_2",
        shop_name: "The Banaras Edit",
        name: "Rose Gold Jhumkas",
        slug: "rose-gold-jhumkas",
        category: "Jewellery",
        description: "Lightweight rose gold-toned jhumkas selected for mehendi and wedding guest looks.",
        price: 2490,
        compare_at_price: 3190,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 14,
        badge: "Bestseller",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_5",
        shop_id: "shop_2",
        shop_name: "The Banaras Edit",
        name: "Banarasi Silk Saree",
        slug: "banarasi-silk-saree",
        category: "Saree",
        description: "Authentic Banarasi silk saree with gold zari work. Perfect for weddings and formal events.",
        price: 12990,
        compare_at_price: 17990,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 3,
        badge: "Exclusive",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_6",
        shop_id: "shop_2",
        shop_name: "The Banaras Edit",
        name: "Silk Printed Dupatta",
        slug: "silk-printed-dupatta",
        category: "Accessories",
        description: "Premium silk dupatta with traditional motifs. A versatile accessory to complete your ethnic look.",
        price: 1890,
        compare_at_price: 2590,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 20,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Ahmedabad Heritage
    {
        id: "prod_7",
        shop_id: "shop_3",
        shop_name: "Ahmedabad Heritage",
        name: "Traditional Bandhani Saree",
        slug: "bandhani-saree",
        category: "Saree",
        description: "Traditional tie-and-dye bandhani saree with intricate patterns. A classic Ahmedabad heritage piece.",
        price: 3990,
        compare_at_price: 5490,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 10,
        badge: "Handmade",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_8",
        shop_id: "shop_3",
        shop_name: "Ahmedabad Heritage",
        name: "Hand Embroidered Choli",
        slug: "embroidered-choli",
        category: "Blouses",
        description: "Beautifully hand-embroidered choli with traditional Ahmedabad patterns. Perfect for traditional occasions.",
        price: 2290,
        compare_at_price: 3190,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 12,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_9",
        shop_id: "shop_3",
        shop_name: "Ahmedabad Heritage",
        name: "Printed Cotton Fabric",
        slug: "printed-cotton",
        category: "Fabric",
        description: "Traditional printed cotton fabric with block print designs. Per meter fabric for custom tailoring.",
        price: 490,
        compare_at_price: 690,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 50,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Modern Threads Ahmedabad
    {
        id: "prod_10",
        shop_id: "shop_4",
        shop_name: "Modern Threads Ahmedabad",
        name: "Fusion Printed Kurta",
        slug: "fusion-printed-kurta",
        category: "Fusion",
        description: "Contemporary kurta with traditional Ahmedabad print patterns. Perfect for modern occasions.",
        price: 1890,
        compare_at_price: 2690,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 18,
        badge: "New",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_11",
        shop_id: "shop_4",
        shop_name: "Modern Threads Ahmedabad",
        name: "Contemporary Suit with Traditional Embroidery",
        slug: "contemporary-suit",
        category: "Fusion",
        description: "Modern suit design with traditional embroidery detailing. Bridge between contemporary and traditional.",
        price: 4490,
        compare_at_price: 6290,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 8,
        badge: "Featured",
        is_featured: true,
        is_active: true,
        created_at: new Date().toISOString()
    },
    // Crafted by Ahmedabad
    {
        id: "prod_12",
        shop_id: "shop_5",
        shop_name: "Crafted by Ahmedabad",
        name: "Handwoven Cotton Saree",
        slug: "handwoven-cotton-saree",
        category: "Saree",
        description: "Authentic handwoven cotton saree from Ahmedabad. Sustainable and comfortable for everyday wear.",
        price: 2890,
        compare_at_price: 3990,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 12,
        badge: "Eco-Friendly",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_13",
        shop_id: "shop_5",
        shop_name: "Crafted by Ahmedabad",
        name: "Artisan Collaboration Shawl",
        slug: "artisan-shawl",
        category: "Accessories",
        description: "Beautiful shawl created through direct collaboration with local Ahmedabad artisans. Each piece supports traditional crafts.",
        price: 3490,
        compare_at_price: 4990,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 6,
        badge: "Fair Trade",
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString()
    },
    // Additional Products - More Variety
    {
        id: "prod_14",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Gold Embellished Saree",
        slug: "gold-embellished-saree",
        category: "Saree",
        description: "Stunning saree with gold embellishment and traditional patterns.",
        price: 7990,
        compare_at_price: 10990,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 9,
        badge: "Premium",
        is_featured: true,
        is_active: true,
        created_at: new Date().toISOString()
    },
    {
        id: "prod_15",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Beaded Blouse",
        slug: "beaded-blouse",
        category: "Blouses",
        description: "Intricately beaded blouse perfect for pairing with sarees.",
        price: 2490,
        compare_at_price: 3490,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 20,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_16",
        shop_id: "shop_2",
        shop_name: "The Banaras Edit",
        name: "Pearl Necklace Set",
        slug: "pearl-necklace-set",
        category: "Jewellery",
        description: "Classic pearl necklace set with matching earrings and bracelet.",
        price: 3990,
        compare_at_price: 5490,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 11,
        badge: "Bestseller",
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_17",
        shop_id: "shop_2",
        shop_name: "The Banaras Edit",
        name: "Evening Gown Style Saree",
        slug: "evening-gown-saree",
        category: "Saree",
        description: "Modern draping style saree perfect for evening events.",
        price: 5490,
        compare_at_price: 7990,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 7,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_18",
        shop_id: "shop_3",
        shop_name: "Ahmedabad Heritage",
        name: "Indigo Dyed Cotton Saree",
        slug: "indigo-cotton-saree",
        category: "Saree",
        description: "Beautiful indigo dyed cotton saree with traditional patterns.",
        price: 2290,
        compare_at_price: 3190,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 16,
        badge: "Eco-Friendly",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_19",
        shop_id: "shop_3",
        shop_name: "Ahmedabad Heritage",
        name: "Traditional Kediyu",
        slug: "traditional-kediyu",
        category: "Traditional",
        description: "Authentic Gujarati traditional jacket with embroidery.",
        price: 3490,
        compare_at_price: 4990,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 8,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_20",
        shop_id: "shop_4",
        shop_name: "Modern Threads Ahmedabad",
        name: "Printed Palazzo Set",
        slug: "printed-palazzo-set",
        category: "Fusion",
        description: "Comfortable printed palazzo set perfect for casual wear.",
        price: 2890,
        compare_at_price: 4290,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 22,
        badge: "New",
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_21",
        shop_id: "shop_4",
        shop_name: "Modern Threads Ahmedabad",
        name: "Embroidered Jacket",
        slug: "embroidered-jacket",
        category: "Outerwear",
        description: "Stylish jacket with traditional embroidery detailing.",
        price: 3890,
        compare_at_price: 5290,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 10,
        badge: "Featured",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_22",
        shop_id: "shop_5",
        shop_name: "Crafted by Ahmedabad",
        name: "Organic Cotton Kurta",
        slug: "organic-cotton-kurta",
        category: "Fusion",
        description: "Comfortable organic cotton kurta with natural dyes.",
        price: 1890,
        compare_at_price: 2890,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 25,
        badge: "Eco-Friendly",
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_23",
        shop_id: "shop_5",
        shop_name: "Crafted by Ahmedabad",
        name: "Hand Painted Fabric",
        slug: "hand-painted-fabric",
        category: "Fabric",
        description: "Beautiful hand-painted fabric per meter for custom designs.",
        price: 590,
        compare_at_price: 890,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 40,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_24",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Stone Work Lehenga",
        slug: "stone-work-lehenga",
        category: "Lehenga",
        description: "Exquisite lehenga with intricate stone work.",
        price: 9990,
        compare_at_price: 13990,
        currency: "INR",
        image_url: "/shop-assets/products/jewellery-1.jpg",
        hover_image_url: "/shop-assets/products/jewellery-2.jpg",
        stock: 4,
        badge: "Exclusive",
        is_featured: true,
        is_active: true,
        created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: "prod_25",
        shop_id: "shop_1",
        shop_name: "Jaipur Atelier House",
        name: "Sequined Top",
        slug: "sequined-top",
        category: "Tops",
        description: "Glamorous sequined top perfect for parties.",
        price: 1890,
        compare_at_price: 2690,
        currency: "INR",
        image_url: "/shop-assets/products/jacket-3.jpg",
        hover_image_url: "/shop-assets/products/jacket-4.jpg",
        stock: 18,
        badge: null,
        is_featured: false,
        is_active: true,
        created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString()
    }
];

export const MOCK_COLLECTIONS = [
    {
        id: "coll_1",
        name: "Festive Essentials",
        slug: "festive-essentials",
        description: "Celebrate in style with our festive collection. Featuring traditional and fusion pieces perfect for festivals and celebrations."
    },
    {
        id: "coll_2",
        name: "Wedding Special",
        slug: "wedding-special",
        description: "Perfect pieces for your special day. From bridal wear to wedding guest outfits, find everything you need."
    },
    {
        id: "coll_3",
        name: "Daily Comfort",
        slug: "daily-comfort",
        description: "Comfortable yet stylish everyday wear. Perfect for work, casual outings, or lounging at home."
    },
    {
        id: "coll_4",
        name: "Designer Collection",
        slug: "designer-collection",
        description: "Curated selection of premium designer pieces from renowned Indian designers."
    },
    {
        id: "coll_5",
        name: "Sustainable Fashion",
        slug: "sustainable-fashion",
        description: "Eco-friendly and sustainable fashion pieces made with handwoven textiles and natural dyes."
    },
    {
        id: "coll_6",
        name: "Summer Vibes",
        slug: "summer-vibes",
        description: "Light, breathable, and cool summer collection perfect for the warm season."
    }
];
